### ISSUE TITLE
Coupled wellbore feature

### ISSUE THREAD

**Issue by Dagurinn** [acroucher/PyTOUGH#12]
There doesn't seem to be any command to utilize the coupled wellbore feature in TOUGH2, that is , you can't specify a well type as for example "fb12d". Is there a workaround, is the feature just missing or am I simply missing something?

**Comment by Dagurinn** [comment]
Sorry, just had a better look at this. The issue is that it has to be 4 letters it seems, so I can call it "fb12" but not "fb12d". Is there a way to extend this limit?

**Comment by acroucher** [comment]
Unfortunately not, that's a limitation of the TOUGH2 input specification. Generator names can only be 5 characters long, and you need one for the 'f' at the start, so there are only 4 left.
