### ISSUE TITLE
Deliverability wells

### ISSUE THREAD

**Issue by Dagurinn** [acroucher/PyTOUGH#13]
I'm trying to run a well on deliverability using PyTOUGH, assigning the well type is simple enough but I can't see any info on how assign the wellbottom pressure to the well. Am I missing something or is this somply not currently included in PyTOUGH?

**Comment by acroucher** [comment]
hi, sorry for slow response, I've been away on holiday. Assuming you want to use a DELV generator type, in PyTOUGH you should create a t2generator object and set its type property to 'DELV'. For DELV generators in TOUGH2, the bottomhole pressure is specified using the 'EX' variable. In PyTOUGH you set the value of that using your generator's ex property, e.g.:

`gen = t2generator(type = 'DELV', ex = 2.e5)`

(if you wanted bottomhole pressure of 2 bars).

For this type of generator you probably want to set the gx property as well, which controls the productivity index.
