### ISSUE TITLE
2-D radial model with topography

### ISSUE THREAD

**Issue by S-Nari** [acroucher/PyTOUGH#20]
Hello.

I have been run some calculation using PyTough, and I'm grateful for it.
So far, I made radial model without topography by using t2grid().radial(dr, dz, atmos_type=0).
Now, I want to made radial model with topography.
I found how to incorporate DEM into 3-D model ( fit_surface() )in the Pytough manual, 
but I didn't find how to build 2-D radial model with topography.
I would appreciate if you let me know how to build a radial model with topography.

Best regards,
Shohei

**Comment by acroucher** [comment]
What sort of system are you trying to model? In most cases it does not make much sense to specify topography on a radial model, because the radial symmetry implies that the topography is also radially symmetrical. So it could make sense if you are modelling a symmetrical radial system, e.g. a cone-shaped mountain (Mt Fuji?), but otherwise it usually isn't what you want. That's why there is no provision in t2grid.radial() for specifying topography.

**Comment by S-Nari** [comment]
Yes, I want to model symmetrical topography like a cone-shaped mountain. Is there other ways to express radial topography? For example, can I make radial topography by adding blocks on the flatten radial model, or removing blocks from the model, after I make a radial model by t2grid.radial()?

**Comment by acroucher** [comment]
OK, in that case, probably the easiest way to do it would be to create your grid using `t2grid.radial()`, with no topography, and then delete the blocks above the ground surface using `t2grid.delete_block()`. (You can decide which blocks to delete by checking their centres.) This will also delete any connections to the deleted blocks.

If you want atmospheric boundary conditions at the surface (which you probably do), then you will also need to add new atmosphere connections, from the atmosphere blocks to the new surface blocks. And make sure you don't delete the atmosphere blocks when you are deleting the other ones.

**Comment by S-Nari** [comment]
Thank you for your advice.
I successfully removed blocks from radial model built by "t2grid.radial()".
And now, I'm trying "add_connection" to connect atmospheric block to the new surface, but I don't understand how to use it at all.
I tried as follows:
dat.grid.add_connection("  a 0", "  a 6") and ("  a 0:  a 6"),
where "  a 0" is an atmospheric block, and "  a 6" is a block on the new surface,
but it didn't work.
Please tell me basic usage of this command (I could not understand although I read a manual...).

**Comment by S-Nari** [comment]
Thank you for your advice.
I successfully removed blocks from the radial model built by "t2grid.radial()",
and connected atmospheric blocks to the new surface ones just below each atmospheric blocks.

Now, I want to make mulgrid geometry from the TOUGH2 grids with topography.
I tried dat.grid.rectgeo(atmos_type=1, atmos_volume=1e+24), and I got the mulgraph geometry.
However, I got the following error when I wrote the t2grid file intoa  vtu file by "dat.grid.write_vtk()" :
----------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/narinari/iwo_proc/frac3/topo_test/topo_rectgeo.py", line 253, in <module>
    dat.grid.write_vtk(geo1,'topo_iwo.vtu')
  File "/usr/lib/python2.7/site-packages/t2grids.py", line 560, in write_vtk
    grid_arrays = self.get_vtk_data(geo, blockmap)
  File "/usr/lib/python2.7/site-packages/t2grids.py", line 539, in get_vtk_data
    rindex = self.get_rocktype_indices(geo, blockmap)
  File "/usr/lib/python2.7/site-packages/t2grids.py", line 509, in get_rocktype_indices
    for blkname in geo.block_name_list])
KeyError: '  a 1'
-----------------------------------------------------------------------------------------------------------
It says like that a block "  a 1", which is top layer of the first column, could not be found in the mulgrid file, but I can see the block "  a 1" in the file.
If you know something about this error, please give me a hint.

**Comment by acroucher** [comment]
I am not sure whether `t2grid.rectgeo()` will work in this situation. It assumes a rectangular grid, so the `mulgrid` it produces may not be correct for a radial grid, especially as you have manually edited the radial grid to remove blocks above the ground surface. It sounds like there is probably some inconsistency between the block names in your `mulgrid` and the `t2grid`.

It might be safer to construct your `mulgrid` using the `mulgrid.rectangular()` method instead. You can specify the same radial and vertical grid spacings you used to create the radial grid, and then use the `mulgrid.fit_surface()` method to set the appropriate surface elevation for each column. To do this, you can make up a surface elevation dataset with (r, y, z) data for your topography and pass that in to `fit_surface()`.

Even in this case you should carefully check that the block names are completely consistent between the `mulgrid` and the `t2grid`- e.g. by comparing the `mulgrid`'s block_name_list property with the names of the blocks in the `t2grid`'s block list.
