### ISSUE TITLE
 How to have a VTK ASCCI file ( not the default mode binary)

### ISSUE THREAD

**Issue by aaamri** [acroucher/PyTOUGH#24]
Hi everyone, Hi Adrian
Thanks for your effort for PYTOUGH, it's very helpful, i want to know if there's a possibility to have a ASCCI VTK file  and note a vtu Binary file.
THnak you !

**Comment by acroucher** [comment]
At the moment it is hard coded to write a *.vtu file. Is there a particular reason you want an ASCII *.vtk file? Usually the binary files are much smaller and faster to load.

**Comment by aaamri** [comment]
Thnaks Adrian for your response. i will work with the binary version.
