### ISSUE TITLE
Plotting contours using slice_plot function not working

### ISSUE THREAD

**Issue by quenchlemon** [acroucher/PyTOUGH#32]
Hi acroucher,

I have an issue plotting contours using the slice_plot function and am wondering whether it is due to an incompatibility of the packages? The error I am getting can be found in the image below:

![Code_El7HUYnaGY](https://user-images.githubusercontent.com/5679441/144964494-278dc2fd-918a-440d-8ff3-9e53c280bce1.png)

Packages used 
Python 3.7.12, 
Numpy 1.21.4 
Matplotlib 3.5.0
Scipy 1.7.3
and the latest version of PyTOUGH.

**Comment by acroucher** [comment]
hi Jonathan, yes there were some changes in Matplotlib 3.1 which were not backwards compatible. The next release of PyTOUGH will be updated to reflect these changes. Meanwhile if you run the 'testing' branch (rather than 'master') it should work ok.

**Comment by quenchlemon** [comment]
Ok great. I can confirm that the PyTOUGH-testing version works with the above mentioned packages.

Thanks!
