### ISSUE TITLE
changing rock block name

### ISSUE THREAD

**Issue by jousheinfo** [acroucher/PyTOUGH#38]
Hi, thanks for sharing the code. My question is the following: when I want to write any other different name than "dfalt", let's say "wella", there is an error. Could you help me, please? Thanks a lot!

**Comment by acroucher** [comment]
I'd need to see a bit more detail of what you're doing. But your issue is called "changing rock block name", and "dfalt" is the default rock type name (not block name). "wella" could not be used as a block name as it does not end in two digits (required by TOUGH2).
