### ISSUE TITLE
INCON block data

### ISSUE THREAD

**Issue by jousheinfo** [acroucher/PyTOUGH#39]
Hi, I am trying to set my INCON block data up, but I have the following problem: I have 2 separated dataframes Pwell for pressure (X1) and Twell for temperature (X4) and want to iterate though all the element of each dataframe and take those values as X1 and X4. Here is part of the code:

![PYTOUGH INCON](https://user-images.githubusercontent.com/104328660/167250601-58c71ebc-a14e-4d8d-8a93-33776636214a.PNG)

But, for any reason it only takes the first value of the DataFrame even though it is been iterated.

![INCON input file](https://user-images.githubusercontent.com/104328660/167250674-b308629a-bff3-46dc-af84-abec63342543.PNG)

I have been trying everything, I converted the DataFrame to list or array, but nothing works. I also tried the function extend(), but it takes the first 4 elements of the first dataframe Pwell horizontally and then it repeats in all rows. I would very much appreciate your help. Thank you for your time!

**Comment by acroucher** [comment]
It looks to me like you are using PyTOUGH correctly in the script. But I am not that familiar with DataFrames, so I don't know if how you are getting the data out of Pwell and Twell is correct or not.
