### ISSUE TITLE
VTK export from TOUGHREACT

### ISSUE THREAD

**Issue by nikolai-andrianov** [acroucher/PyTOUGH#46]
Thanks for pyTOUGH, has been quite useful!

The `write_vtk` method of `toughreact_tecplot` yields an error when exporting TOUGHREACT simulation results to VTK in `get_vtk_data` around line 1804 of `t2listing.py`. Apparently this happens when `geo_matches == False` in this subroutine which is always the case due to the comparison 

    geo_matches = geo.block_name_list == self.element.row_name

in `write_vtk` (which always gives `False` because a list is compared to a dict).

A workaround is to replace this comparison by 

    geo_matches = geo.block_name_list == list(self.element.row_name.keys())

**Comment by acroucher** [comment]
The ``self.element.row_name`` variable should be of type ``list``, not ``dict``.

Is it possible you are passing in a ``dict`` for the ``blocks`` parameter when you create your ``toughreact_tecplot`` object?

The blocks parameter should be either a ``list``, a ``mulgrid`` or a ``t2grid``. A ``dict`` can't be used because the order of the block names is important.

**Comment by nikolai-andrianov** [comment]
The `toughreact_tecplot` object is created from `dat.grid.block`, which is in turn created by calling the `t2grid()` constructor. So when I call `write_vtk` method of `toughreact_tecplot`, `self.element.row_name` **is** a `dict`, not `list`. See an example script `tough_cpg.py` at https://github.com/nikolai-andrianov/TOUGH-CPG.

**Comment by acroucher** [comment]
You should just pass in `dat.grid` for the blocks parameter, not `dat.grid.block`. As the user guide says, this parameter should be either a list of strings, a `mulgrid` geometry object or a `t2grid` object.

For example, line 469 in your script should be:

```python
lst = toughreact_tecplot(folder + '/flowdata.tec', dat.grid)
```

**Comment by nikolai-andrianov** [comment]
That works, thanks a lot!
