### ISSUE TITLE
About install PyTOUGH

### ISSUE THREAD

**Issue by wsc1008-cugb** [acroucher/PyTOUGH#48]
I downloaded the PyTOUGH zip file, and then install it in the Pycharm. But it doesn't appear in the site-packages file, only has these information. How could I use the PyTOUGH normally.
![1687142044521(1)](https://github.com/acroucher/PyTOUGH/assets/74029851/0644c5ec-0370-4b0a-9cec-545389c86130)

**Comment by acroucher** [comment]
If you have successfully installed PyTOUGH, you should be able to open a Python command-line prompt and import PyTOUGH modules, e.g.:

```bash
acro018@en-354401:~$ python
Python 2.7.13 (default, Feb  6 2022, 20:16:18) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from mulgrids import *
>>> 
```
