### ISSUE TITLE
PyTOUGH Installation

### ISSUE THREAD

**Issue by jousheinfo** [acroucher/PyTOUGH#50]
Dear @acroucher,

I had PyTOUGH already working, but suddenly it stopped. I did the steps as specified here, but I get the following error in the command prompt:

setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
running install
running build
running build_py
running install_lib
running install_egg_info
Removing C:\Users\User\AppData\Local\Programs\Python\Python310\Lib\site-packages\PyTOUGH-1.5.6-py3.10.egg-info
Writing C:\Users\User\AppData\Local\Programs\Python\Python310\Lib\site-packages\PyTOUGH-1.5.6-py3.10.egg-info

I would very much appreciate your support, please. Thanks!

**Comment by acroucher** [comment]
That doesn't look like an error, just a "deprecation warning" - it's saying the distutils package that PyTOUGH uses to install will be removed in future. Does PyTOUGH work again?

**Comment by acroucher** [comment]
PyTOUGH 1.6.0 has revised packaging and features easier installation via `pip install PyTOUGH`.
