### ISSUE TITLE
Distribute package on PyPI?

### ISSUE THREAD

**Issue by matthewfeickert** [acroucher/PyTOUGH#55]
:wave: @acroucher would you be open to the idea of publishing and distributing PyTOUGH on PyPI? This has become relevant in at least one case for a paper review (c.f. https://github.com/openjournals/joss-reviews/issues/6125#issuecomment-1901093941).

If so (great!), if you have any questions about how to do so, please check the [Python Packaging User Guide's section on Packaging Python Projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/) and the [Scientific Python Development Guide](https://learn.scientific-python.org/development/guides/) topical guide on packaging which includes information on how to get started with deployment to PyPI.

**Comment by acroucher** [comment]
I've just released version 1.6.0 which has pip install from PyPI and modernized packaging using pyproject.toml (as well as migrating the PDF user guide to Read the Docs).
